### ISSUE TITLE
New lot-no.  2112101 leads to error while using bletl.parse()

### ISSUE THREAD

**Issue by LarsHalle** [JuBiotech/bletl#17]
```python
bletl.parse('filename', lot_number=2112101, temp=30)
```

Error message:
```
InvalidLotNumberError: Latest calibration information was downloaded from m2p-labs, but the provided lot number/temperature combination (lot_number=2112101, temp=30) could not be found. Please check the parameters.
```

**Comment by michaelosthege** [comment]
@LarsHalle try to call [`bletl.utils.download_calibration_data()`](https://github.com/JuBiotech/bletl/blob/ad4d5b9d3807be8627ada45240b4598f7a84756f/bletl/utils.py#L185-L209) manually.
But since this should have happened automatically, it probably won't help.

Next you can then look into these files manually. They will be somewhere under the following path:
```python
import bletl
print(bletl.__path__[0])
```

Check them in Notepad++ to see if they contain your lot number. Maybe you must pass it in a different format.

FYI: If you had the lot number programmed into the BioLector protocol there should be no need to pass it manually, since it's automatically contained in the result file. (Same for the temperature.)

**Comment by LarsHalle** [comment]
I spoke to Beckmann and they have added the missing callibration data to the files for BLI :-)
