### ISSUE TITLE
Cycle count not uniform in .fluidics and .parse

### ISSUE THREAD

**Issue by katroh** [JuBiotech/bletl#42]
Dataframes generated with `bletl.parse.fluidics` start at cycle count 0, while dataframes generated with `bletl.parse.get_unified_narrow_data()` start at cycle count 1.
In my opinion, both should start at cycle count 1.

**Comment by michaelosthege** [comment]
@bertramgeinitz and I investigated this. We found that:
* Triggers are evaluated after the last filterset measurement was completed.
* The data ending up in the `fluidics` table is written at the end of a cycle (right before the next one starts).
* It **refers to the volumes at the end of the cycle** (e.g. the `"volume"` at the end of the cycle).
* The `fluidics` row of the last cycle is always missing, because processes stop immediately, or after the last filterset without waiting for the pumping in that cycle to complete, and without writing final volumes to the resultfile.

I considered to add another column to the `fluidics`, with volumes referring to the cycle start, but this would create "gaps" and generally increase confusion about the currently available columns.

Consequently, depending on the analysis one should do one of the following:
* Look at the `fluidics.loc[well].set_index("cycle").loc[cycle - 1]` data to get the volumes from when `cycle` _started_.
* Interpolate to get volumes at arbitrary time points.
* Extrapolate to get volumes at specific times within, or at the end of the last available cycle.


Since we found that the cycle numbers in the `fluidics` table is in fact correct, I will close the issue.
